### PR TITLE
Python 3, pypi package, and module support

### LINKED ISSUE #4: Missing setup.py
The package is missing a setup.py along with the following:
- mpyq should be removed from this repo
- a requirements.txt should be added and included in the setup.py install requirements
- a travis ci build should be setup, even with no tests the travis CI can take care of releasing to pypi

1 and 2 should be doable in a single PR but 3 should probably be done in another repo and by someone at Blizzard.

### LINKED ISSUE #57: How to port the heroprotocol to Python 3
Let me start with saying that I'm not super experienced with Python yet but I'm learning gradually. Can you please assist when I am trying to port the heroprotocol to Python 3? I installed the required library and when I try to run  `header = protocol.decode_replay_header(mpq.header['user_data_header']['content'])` I get this error: `TypeError: ord() expected string of length 1, but int found`. The error says that it's in the decoders.py file on the row 69. Just to clarify, I am using latest Anaconda release. Thanks for any help.

### LINKED ISSUE #88: Restore Python 2 Compatibility
The Python 3 update broke compatibility with Python 2, specifically around how modules from the `heroprotocol.versions` package are imported, and perhaps elsewhere.

Is there impetus to continue to support Python 2?

### PR DESCRIPTION
**Pull request by Agilhardt**
- Updates to support both Python 2.7 and Python 3.x
- Package now publishes to PyPI (https://pypi.org/project/heroprotocol)
- New method of invoke, instead of `python heroprotocol.py [...]`, run `python -m heroprotocol [...]`. This works either with the PyPI package installed, or running from source at the checkout root.

Resolves #4, resolves #5, resolves #57, resolves #59, resolves #85, resolves #86, resolves #88.

### CODE REVIEW

**Comment by Agilhardt** [comment]
I'm going to leave this here to soak for a week or two. @MGatner, @Astraeus-, @patonz, and anyone else who is using this library directly, please test it and send feedback.
Also, please test the published package is available on PyPI: `pip install --upgrade heroprotocol`.

**Comment by ebshimizu** [comment]
While not exactly a python use case, the javascript parser ([nydus/heroprotocol](https://github.com/nydus/heroprotocol)) downloads the protocol files and uses them as templates for its implementation. It looks like that package will be ok with the changes once the path to the protocol files is updated. Thankfully, that's a super small change to make (not sure if the maintainer for that project is still around), and it looks like the package is working correctly on the develop branch. Will do a bit more testing this weekend.

**Comment by patonz** [comment]
Got some issues with alpine during docker build, i will check again asap

**Comment by Agilhardt** [comment]
> Got some issues with alpine during docker build, i will check again asap

@patronz Good catch, `six` is missing from the pypi package requirements. Will address with the next push. For now you can `pip install six` as a workaround.

**Comment by ebshimizu** [comment]
> While not exactly a python use case, the javascript parser ([nydus/heroprotocol](https://github.com/nydus/heroprotocol))...

Ran through a few hundred recent replays using the develop branch with nydus/heroprotocol this weekend and it looks like it's working just fine. Should be good to go there.

**Comment by Agilhardt** [comment]
For awareness, I published `heroprotocol-2.50.1.79515.post1` to PyPI which resolves the missing dependency.
https://pypi.org/project/heroprotocol/2.50.1.79515.post1/

**Pull request merged**
