### PR TITLE
adding --json to heroprotocol.py to dump json instead of pprint

### PR DESCRIPTION
**Pull request by bryanar**
Added --json to heroprotocol.py to dump json instead of pprint.

Also, I threw in a batch file that, when directed at a replay and output folder, will extract all available information and places it in a folder that matches the replay's name.

I'm calling this an explorative PR to see how Blizzard handles things, be liberal with the feedback it is much appreciated.

### CODE REVIEW

**Comment by surgun9** [comment]
@bryanar, is there a way to get data in UTF-8 format?

**Comment by Farof** [comment]
I hope Blizzard does something with the pull requests and adds an easy way to get a JSON output, but in the meantime you can check out my Javascript port that runs on NodeJS if you want: [Farof/heroprotocoljs](https://github.com/Farof/heroprotocoljs).

Just use the `bin/extract.js` tool and you can extract any number of files or entire directories of replays at once.

**Comment by bryanar** [comment]
@surgun9 I think there is. I just didn't want to take the time to figure it out the other day. I don't know crap about python, but it must default to iso 8859-1 or something. I saw some sample code the other day that worked around it. I will see if I can find it and make amends shortly (like within an hour or two).

**Comment by bryanar** [comment]
@Farof O.O I love you. I don't know much about JavaScript either (predominantly C++/Java guy) but I have been meaning to figure it out for the sake of playing with the replays and what I want to do with them. This set of code will be taking up some time tonight as well :) Thanks for the work.

**Comment by bryanar** [comment]
This SO seems to explain what is happening: http://stackoverflow.com/questions/23887124/python-json-ignoring-non-ascii-chars-unicodedecodeerror-ascii-codec-cant-deco

**Comment by bryanar** [comment]
It seems to be because this piece of data, which according to the details data are the cache handles. 

 ["s2ma\u0000\u0000US\u001f\u001b\"**\u008d**\u00db\u001fr \\\u00bf\u00d4D\u0005R\u0087\u0010\u000b\u000f9\u0095\u009b\u00e8\u0016T\u0081b\u00e4\b\u001e\u00a8U\u0011", "s2ma\u0000\u0000US\u001a\u00d9L\u0012n\u00b9\u008aL\u001d\u00e7\u00b8\u00e6\u00f8\u00aa\u00a1S\u00db\u00a5+\t\u00d3\u0082^\f\u0089\u00db\u00c5\u0082\u008d\u00b7\u000fv", "s2ma\u0000\u0000US\u0092\u00d8\u0017D\u00c1D\u001b\u00f6(\u00edj\u00b7\u00e9\u00d1\u0094\u0085\u00c8`\u0091M\u008btZ\u0091\u00f65\u001f\u00f9\u00dc\u00d4\u00e6\u00bb", "s2ma\u0000\u0000US\u00a1\u00e9\u00ab\u00cd?\u00d2PS\u00c9\u0003\u00ab\u0013R\u00a6\u0085u7(K2\u009d\b\u00b8k+\u00e2\u00deI\u00c3\u00ab\u007fC", "s2ma\u0000\u0000US\u00db#\u00ab\u00e8:\u008bHn\u0095\u00c2\u00e9-\u00de\u00ebU\u00c3\u00f3\u00c7\u0003\u0094E\u00af\u0091\u00dbX23\u000f\u00bdx\u008d\u00f8", "s2ma\u0000\u0000US\u0017\u00f6\u0090NX\u00beJ\u0081\\\u0091z\u008eF(\u00c65\u00fd\u00f5\u008a\u0096z\u00f8\u0094w\u0099\u00f5\u00a2\u0013\u00ee\u00ca)G", "s2ma\u0000\u0000US_\r\u00eci\u00ae\u009b\u00c3\u00c8\u0015\u00c2\u00ef\\p'l\u008d\u00bbF\u00a4\u00a7\u00c6W\u00cf6\u00d2\u00dd\u0085\u0096\u001b\u0016A\u0012"]

**Pull request merged**
